USE gcc_circle;

INSERT INTO events
(name,slug,city,date,type,cover_image,attendees,leaders,description,images,registration_link,registrations_open,active)
VALUES
(
'Bangalore Tech Leadership Mixer',
'bangalore-feb-2026',
'Bangalore',
'13th February 2026',
'Tech Leadership Mixer',
'https://images.unsplash.com/photo-1588416936097-41850ab3d86d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
55,
'[{"name": "Smita Singh", "company": "Simplr"}, {"name": "Abhishek Parkala", "company": "Innovapptive"}, {"name": "Vanita Aggarwal", "company": "EPAM"}, {"name": "Ramya Shreekantj", "company": "Zinnov Management Consulting"}, {"name": "Karthikeya Bhaghavatula", "company": "Maersk"}, {"name": "Vidit Jain", "company": "Scaler"}, {"name": "Preeth Zachariah", "company": "VOIS"}, {"name": "Shaji Namath", "company": "Honeywell"}, {"name": "Priji Thomas", "company": "Flexera"}, {"name": "Vinay Muniyappa", "company": "ByldBridge"}, {"name": "Mudit Mehrotra", "company": "IBM Limited"}, {"name": "Shubham Srivastava", "company": "Salesforce"}, {"name": "Lukos L", "company": "MetricStream"}, {"name": "Aneelkumar Savalagi", "company": "Takeda Innovations India Private Limited"}, {"name": "Lalit Mittal", "company": "State Street Investment Management"}, {"name": "Vadivelan Gopal", "company": "Scaler"}, {"name": "Prabhas Abhayakumar", "company": "TRG Screen"}, {"name": "Gaurav Khanna", "company": "CommerceIQ"}, {"name": "Ketan Dave", "company": "JPMC"}, {"name": "Atul Kumar Rai", "company": "Fossil Group"}, {"name": "Sankar Pantula", "company": "Pretium India"}, {"name": "Anil Pillai", "company": "Independent Consultant"}, {"name": "Ravindra Seshagiri Hassan", "company": "Pluralsight (Ex)"}, {"name": "Rashmi", "company": "Expedia"}, {"name": "Kevin D''souza", "company": "GE Healthcare"}, {"name": "Vinay Anand", "company": "Google"}, {"name": "Rachit Trivedi", "company": "Mitel"}, {"name": "Vishal Chopra", "company": "Accenture"}, {"name": "Arun Dutta", "company": "HighRadius"}, {"name": "Randhir Bindra", "company": "Booking Holdings"}, {"name": "Uma Seetharaman", "company": "Legal Zoom"}, {"name": "Akhil Sikri", "company": "Apsona"}, {"name": "Swayta", "company": "HSBC"}, {"name": "Sripathy S", "company": "Cargill"}, {"name": "Paras Nigam", "company": "ICIMS"}, {"name": "Sudhakar Nagandla", "company": "ECU Worldwide"}, {"name": "Balajinrajan", "company": "Pasarpolis.com"}, {"name": "Meghana Alexander", "company": "Mercedes Benz Research & Development India"}, {"name": "Kaustubh Deshpande", "company": "SAP Fioneer"}, {"name": "Srinivas Chamarthy", "company": "Diligent"}, {"name": "Ramaswamy Narayanan", "company": "Bridgepath Innovations"}]',
'<p>The GCC Circle Mixer | Bengaluru, brought together a curated group of senior GCC leaders for an evening of candid conversations and meaningful connections. Designed as a closed-door gathering, the mixer focused on peer-level exchange, shared context, and real-world insights shaping India’s Global Capability Centres. Hosted in partnership with Scaler School of Technology and powered by Talentiser, the evening reflected a shared commitment to building future-ready GCC leadership.</p>',
'["/events/feb-2026-bangalore/images/3.jpg", "/events/feb-2026-bangalore/images/4.jpg", "/events/feb-2026-bangalore/images/5.jpg", "/events/feb-2026-bangalore/images/6.jpg", "/events/feb-2026-bangalore/images/7.jpg", "/events/feb-2026-bangalore/images/8.jpg", "/events/feb-2026-bangalore/images/9.jpg", "/events/feb-2026-bangalore/images/10.jpg", "/events/feb-2026-bangalore/images/11.jpg", "/events/feb-2026-bangalore/images/12.jpg", "/events/feb-2026-bangalore/images/13.jpg", "/events/feb-2026-bangalore/images/14.jpg", "/events/feb-2026-bangalore/images/15.jpg", "/events/feb-2026-bangalore/images/16.jpg", "/events/feb-2026-bangalore/images/17.jpg", "/events/feb-2026-bangalore/images/18.jpg", "/events/feb-2026-bangalore/images/19.jpg", "/events/feb-2026-bangalore/images/20.jpg", "/events/feb-2026-bangalore/images/21.jpg", "/events/feb-2026-bangalore/images/22.jpg", "/events/feb-2026-bangalore/images/23.jpg", "/events/feb-2026-bangalore/images/24.jpg", "/events/feb-2026-bangalore/images/25.jpg", "/events/feb-2026-bangalore/images/26.jpg", "/events/feb-2026-bangalore/images/27.jpg", "/events/feb-2026-bangalore/images/28.jpg", "/events/feb-2026-bangalore/images/29.jpg", "/events/feb-2026-bangalore/images/30.jpg", "/events/feb-2026-bangalore/images/31.jpg", "/events/feb-2026-bangalore/images/32.jpg", "/events/feb-2026-bangalore/images/33.jpg", "/events/feb-2026-bangalore/images/34.jpg", "/events/feb-2026-bangalore/images/35.jpg", "/events/feb-2026-bangalore/images/36.jpg", "/events/feb-2026-bangalore/images/37.jpg", "/events/feb-2026-bangalore/images/38.jpg", "/events/feb-2026-bangalore/images/39.jpg", "/events/feb-2026-bangalore/images/40.jpg", "/events/feb-2026-bangalore/images/41.jpg", "/events/feb-2026-bangalore/images/42.jpg", "/events/feb-2026-bangalore/images/43.jpg", "/events/feb-2026-bangalore/images/44.jpg", "/events/feb-2026-bangalore/images/45.jpg", "/events/feb-2026-bangalore/images/46.jpg", "/events/feb-2026-bangalore/images/47.jpg", "/events/feb-2026-bangalore/images/48.jpg", "/events/feb-2026-bangalore/images/49.jpg", "/events/feb-2026-bangalore/images/50.jpg", "/events/feb-2026-bangalore/images/51.jpg", "/events/feb-2026-bangalore/images/52.jpg", "/events/feb-2026-bangalore/images/53.jpg"]',
'',
0,
1
);