USE gcc_circle;

INSERT INTO events (
    name,
    slug,
    city,
    date,
    type,
    cover_image,
    attendees,
    leaders,
    description,
    images,
    registration_link,
    registrations_open,
    active
)
VALUES (
    'Hyderabad Tech Leadership Mixer',
    'hyderabad-december-2025',
    'Hyderabad',
    '5th December 2025',
    'Tech Leadership Mixer',
    'https://images.unsplash.com/photo-1551161242-b5af797b7233?q=80&w=2051&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    45,
    '[
        {"name":"Ravi Wadhwa","company":"Founder, GCC Circle powered by Talentiser"},
        {"name":"Arushi Jindal","company":"GCC Circle"},
        {"name":"Ipsita Dey","company":"Talentiser"},
        {"name":"Jaideep Agarwal","company":"Warner Bros. Discovery"},
        {"name":"Sandeep Kumar Jain","company":"CDK Global India"},
        {"name":"Atul Arora","company":"Crete India"},
        {"name":"Arun Dutta","company":"HighRadius"},
        {"name":"Yogesh Sharma","company":"Quince"},
        {"name":"Sangeetha Yanamandra","company":"OpenText"},
        {"name":"Biju Davis","company":"Invoice Cloud Inc."},
        {"name":"Kartik Balachandran","company":"Providence India"},
        {"name":"Yogesh M.","company":"Cyara"},
        {"name":"Aditya Mony","company":"Servify"},
        {"name":"Pallavi Maheshwari","company":"Redwood"},
        {"name":"Shrinivas Bairi","company":"Plume Design Inc."},
        {"name":"Peddareddappa G","company":"Nasuni"},
        {"name":"Laxmikanth Katheragandla","company":"Jaggaer"},
        {"name":"Sanjeev S.","company":"Reply"},
        {"name":"Phani Kiran","company":"iCIMS"},
        {"name":"Anurag Garg","company":"Ryan"},
        {"name":"Seshu Kumar Loka","company":"Highspot"},
        {"name":"Anumolu Kiran","company":"Kiddie Global Solutions"},
        {"name":"Yagneshwar Sreekanth","company":"GUS Education India"},
        {"name":"Rajesh Ramaswami","company":"Elevance Health"}
    ]',
    '<p>The Hyderabad edition of the GCC Circle Mixer delivered exactly what it set out to create: a room full of senior GCC leaders engaged in sharp, meaningful conversation. From candid exchanges on scaling global capability operations to spontaneous problem-solving huddles, the evening flowed with energy and intent.</p>',
    '[
        "/events/dec-2025-hyderabad/images/Artboard 1.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 2.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 3.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 4.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 5.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 6.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 7.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 8.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 9.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 10.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 11.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 12.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 13.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 14.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 15.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 16.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 17.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 18.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 19.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 20.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 21.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 22.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 23.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 24.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 25.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 26.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 27.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 28.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 29.jpg",
        "/events/dec-2025-hyderabad/images/Artboard 30.jpg"
    ]',
    '',
    0,
    1
);