USE gcc_circle;

INSERT INTO events
(name,slug,city,date,type,cover_image,attendees,leaders,description,images,registration_link,registrations_open,active)
VALUES
(
'Gurugram GCC Inner Circle Roundtable',
'gurugram-august-2026',
'Gurugram',
'2nd July 2026',
'GCC Inner Circle Roundtable',
'',
45,
'[{"name": "Acuity Analytics", "company": ""}, {"name": "Baker & Taylor India", "company": ""}, {"name": "Bain & Company", "company": ""}, {"name": "Bupa", "company": ""}, {"name": "DB Schenker", "company": ""}, {"name": "ETS Assessment Services", "company": ""}, {"name": "EY", "company": ""}, {"name": "Fractal", "company": ""}, {"name": "Hatch", "company": ""}, {"name": "Hub Platform Technology", "company": ""}, {"name": "JAS Worldwide", "company": ""}, {"name": "LiveRamp", "company": ""}, {"name": "Mastech Digital", "company": ""}, {"name": "MongoDB", "company": ""}, {"name": "Morgan Stanley", "company": ""}, {"name": "NatWest Group", "company": ""}, {"name": "Optum", "company": ""}, {"name": "Payoneer", "company": ""}, {"name": "Persol", "company": ""}, {"name": "PwC", "company": ""}, {"name": "S&P Global", "company": ""}, {"name": "Synechron", "company": ""}, {"name": "Teads", "company": ""}, {"name": "Valvoline Cummins", "company": ""}, {"name": "Vertex Inc.", "company": ""}, {"name": "WAIPA", "company": ""}, {"name": "Wio Bank PJSC", "company": ""}]',
'<h2>GCCs in the Decade Ahead: From Delivery Centers to What''s Next?</h2><p>The role of Global Capability Centers (GCCs) is undergoing a profound transformation. Once established primarily as delivery and shared services hubs, today''s GCCs are becoming strategic drivers of innovation, digital transformation, product development, and enterprise leadership.</p><p>To explore what lies ahead, GCC Circle, in partnership with JLL, hosted the inaugural GCC Inner Circle Roundtable—an invite-only leadership forum that brought together some of India''s most influential GCC leaders and enterprise decision-makers for an evening of candid, peer-led conversations.</p><p>Designed as an intimate, closed-door forum, the roundtable moved away from the traditional conference format. There were no presentations, no panels, and no commercial agenda—just meaningful discussions among leaders who are actively shaping the future of India''s GCC ecosystem.</p><h2>Theme</h2><ul><li>The evolving mandate of GCCs within global enterprises</li><li>AI and its impact on operating models, leadership, and talent</li><li>Innovation, product ownership, and enterprise influence</li><li>Building future-ready leadership teams</li><li>Talent, culture, and the future workplace</li><li>Opportunities and challenges shaping the next decade of India''s GCC ecosystem</li></ul><h2>Key Takeaways</h2><ul><li>GCCs are increasingly being entrusted with strategic business outcomes rather than execution alone.</li><li>AI is redefining operating models, leadership expectations, and workforce planning.</li><li>Leadership capability is becoming a stronger differentiator than organisational scale.</li><li>Innovation, product ownership, and enterprise influence are replacing traditional cost-centric success metrics.</li><li>The future of GCCs will be shaped by collaboration, talent transformation, and stronger integration with global business strategy.</li></ul><h2>An Evening of Meaningful Conversations</h2><p>The response from participants was overwhelmingly positive. Leaders appreciated the intimate format, the quality of discussions, and the opportunity to exchange ideas openly with peers in a trusted environment. The success of the inaugural edition reinforces GCC Circle''s commitment to creating meaningful platforms where the industry''s most influential leaders can connect, learn, and collectively shape the future of India''s Global Capability Center ecosystem.</p><p>The success of the mixer reinforced the purpose of the GCC Circle - India''s foremost leadership community for CXOs, Site Heads, and senior leaders shaping the future of global capability centers. Powered by Talentiser, it is becoming a trusted space for decision-makers to engage, exchange, and expand their networks.</p><p>This is just the beginning. More circles, more cities, and more high-calibre leadership experiences are on the way.</p>',
'["/events/july-2026-gurugram/images/Gurugram01.jpeg", "/events/july-2026-gurugram/images/Gurugram02.jpeg", "/events/july-2026-gurugram/images/Gurugram03.jpeg", "/events/july-2026-gurugram/images/Gurugram04.jpeg", "/events/july-2026-gurugram/images/Gurugram05.jpeg", "/events/july-2026-gurugram/images/Gurugram06.jpeg", "/events/july-2026-gurugram/images/Gurugram07.jpeg", "/events/july-2026-gurugram/images/Gurugram08.jpeg", "/events/july-2026-gurugram/images/Gurugram09.jpeg", "/events/july-2026-gurugram/images/Gurugram10.jpeg", "/events/july-2026-gurugram/images/Gurugram11.jpeg", "/events/july-2026-gurugram/images/Gurugram12.jpeg", "/events/july-2026-gurugram/images/Gurugram13.jpeg", "/events/july-2026-gurugram/images/Gurugram14.jpeg", "/events/july-2026-gurugram/images/Gurugram15.jpeg", "/events/july-2026-gurugram/images/Gurugram16.jpeg", "/events/july-2026-gurugram/images/Gurugram17.jpeg", "/events/july-2026-gurugram/images/Gurugram18.jpeg", "/events/july-2026-gurugram/images/Gurugram19.jpeg"]',
'',
0,
1
);
