export const pastEvents = [
    {
      id: "delhi-april-2026",
      city: 'Delhi',
      month: 'April',
      date: '10th',
      year: '2026',
      type: 'Executive Summit',
      img: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      attendees: '60+',
      description1: `The overwhelming response to the mixer underscored the growing need for curated, high-intent GCC leadership communities in India.
        With 700+ registrations, the event saw strong interest from across the ecosystem. A highly selective cohort of 70 senior leaders was shortlisted, with 45+ leaders confirmed, ensuring a room defined by depth, relevance, and peer-level engagement.
        The evening brought together an exceptional mix of leadership from organisations such as Microsoft, Samsung, EY, Bain & Company, Bank of America, GoDaddy, NatWest, S&P Global, Gartner, Genpact, Optum, JLL, Fractal, TransUnion, Bupa Capability Center, LiveRamp, Indeed, Merck Group, Verizon, and Acuity Analytics, among others.
        Together, it marked a powerful step towards building a more connected, collaborative, and future-ready GCC leadership ecosystem in India.
      `,
      description2: `The success of the mixer reinforced the purpose of the GCC Circle - India’s foremost leadership community for CXOs, Site Heads, and senior leaders shaping the future of global capability centers. Powered by Talentiser, it is becoming a trusted space for decision-makers to engage, exchange, and expand their networks.
        This is just the beginning. More circles, more cities, and more high-calibre leadership experiences are on the way.
      `,
      leaders: [
        { "name": "Abhishek Tandon", "company": "Mastech Digital" },
        { "name": "Aditya Waghray", "company": "Microsoft" },
        { "name": "Anirban Sarkar", "company": "Merck Group" },
        { "name": "Ankit Singhal", "company": "Indeed" },
        { "name": "Chakrapani Gollapali", "company": "Wio Bank PJSC" },
        { "name": "Deependra Singh", "company": "GoDaddy" },
        { "name": "Deepika Gandhi", "company": "NatWest" },
        { "name": "Dwaipayan Chakraborty", "company": "JAS Worldwide" },
        { "name": "Himanshu Pahuja", "company": "S&P Global" },
        { "name": "Jagdeep", "company": "Baker & Taylor" },
        { "name": "Jaideep Kumar", "company": "Saasworx" },
        { "name": "Jatinder Singh Guliani", "company": "Gartner" },
        { "name": "Manjeet Singh Chowdhary", "company": "Arietis Health" },
        { "name": "Mayank Agarwal", "company": "Bupa Capability Center" },
        { "name": "Mohit Mittal", "company": "Acuity Analytics" },
        { "name": "Naveen Mishra", "company": "Gartner" },
        { "name": "Neeraj Khatri", "company": "Miyabi Advisors Private Limited" },
        { "name": "Poonam Masand", "company": "Genpact Ltd" },
        { "name": "Puneet Sethi", "company": "Optum" },
        { "name": "Rajat Kapoor", "company": "JLL" },
        { "name": "Rajesh Srivastava", "company": "LiveRamp India Pvt. Ltd." },
        { "name": "Rishi Seth", "company": "Fractal" },
        { "name": "Samta Narula Bhola", "company": "Verizon" },
        { "name": "Vikas Diwvedi", "company": "Evoke PLC" },
        { "name": "Vishal Sukhija", "company": "Smartworks Coworking Spaces Limited" },
        { "name": "Vishesh Goel", "company": "EY" },
        { "name": "Yogendra K Saini", "company": "Aleabodh Labs" },
        { "name": "Aabhas Babar", "company": "Bain & Co" },
        { "name": "Piyush Kukreja", "company": "Samsung" },
        { "name": "Meghaa Khetarpaal", "company": "TransUnion" },
        { "name": "Gaurav", "company": "Samsung" },
        { "name": "Suraj Ganapathi", "company": "Bank of America" }
      ],
      images: [

      ]
    },
    {
      id: "bangalore-feb-2026",
      city: 'Bangalore',
      month: 'February',
      date: '13th',
      year: '2026',
      type: 'Leadership Mixer',
      img: 'https://images.unsplash.com/photo-1588416936097-41850ab3d86d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      attendees: '55+',
      description1: `The GCC Circle Mixer | Bengaluru, brought together a curated group of senior GCC leaders for an evening of candid conversations and meaningful connections. Designed as a closed-door gathering, the mixer focused on peer-level exchange, shared context, and real-world insights shaping India’s Global Capability Centres. Hosted in partnership with Scaler School of Technology and powered by Talentiser, the evening reflected a shared commitment to building future-ready GCC leadership.`,      
      description2: "",
      leaders: [
        { "name": "Smita Singh", "company": "Simplr" },
        { "name": "Abhishek Parkala", "company": "Innovapptive" },
        { "name": "Vanita Aggarwal", "company": "EPAM" },
        { "name": "Ramya Shreekantj", "company": "Zinnov Management Consulting" },
        { "name": "Karthikeya Bhaghavatula", "company": "Maersk" },
        { "name": "Vidit Jain", "company": "Scaler" },
        { "name": "Preeth Zachariah", "company": "VOIS" },
        { "name": "Shaji Namath", "company": "Honeywell" },
        { "name": "Priji Thomas", "company": "Flexera" },
        { "name": "Vinay Muniyappa", "company": "ByldBridge" },
        { "name": "Mudit Mehrotra", "company": "IBM Limited" },
        { "name": "Shubham Srivastava", "company": "Salesforce" },
        { "name": "Lukos L", "company": "MetricStream" },
        { "name": "Aneelkumar Savalagi", "company": "Takeda Innovations India Private Limited" },
        { "name": "Lalit Mittal", "company": "State Street Investment Management" },
        { "name": "Vadivelan Gopal", "company": "Scaler" },
        { "name": "Prabhas Abhayakumar", "company": "TRG Screen" },
        { "name": "Gaurav Khanna", "company": "CommerceIQ" },
        { "name": "Ketan Dave", "company": "JPMC" },
        { "name": "Atul Kumar Rai", "company": "Fossil Group" },
        { "name": "Sankar Pantula", "company": "Pretium India" },
        { "name": "Anil Pillai", "company": "Independent Consultant" },
        { "name": "Ravindra Seshagiri Hassan", "company": "Pluralsight (Ex)" },
        { "name": "Rashmi", "company": "Expedia" },
        { "name": "Kevin D'souza", "company": "GE Healthcare" },
        { "name": "Vinay Anand", "company": "Google" },
        { "name": "Rachit Trivedi", "company": "Mitel" },
        { "name": "Vishal Chopra", "company": "Accenture" },
        { "name": "Arun Dutta", "company": "HighRadius" },
        { "name": "Randhir Bindra", "company": "Booking Holdings" },
        { "name": "Uma Seetharaman", "company": "Legal Zoom" },
        { "name": "Akhil Sikri", "company": "Apsona" },
        { "name": "Swayta", "company": "HSBC" },
        { "name": "Sripathy S", "company": "Cargill" },
        { "name": "Paras Nigam", "company": "ICIMS" },
        { "name": "Sudhakar Nagandla", "company": "ECU Worldwide" },
        { "name": "Balajinrajan", "company": "Pasarpolis.com" },
        { "name": "Meghana Alexander", "company": "Mercedes Benz Research & Development India" },
        { "name": "Kaustubh Deshpande", "company": "SAP Fioneer" },
        { "name": "Srinivas Chamarthy", "company": "Diligent" },
        { "name": "Ramaswamy Narayanan", "company": "Bridgepath Innovations" }
      ],
      images: [

      ]
    },
    {
      id: "hyderabad-december-2025",
      city: 'Hyderabad',
      month: 'December',
      date: '5th',
      year: '2025',
      type: 'CXO Roundtable',
      img: 'https://images.unsplash.com/photo-1551161242-b5af797b7233?q=80&w=2051&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      attendees: '45+',
      description1: `The Hyderabad edition of the GCC Circle Mixer delivered exactly what it set out to create: a room full of senior GCC leaders engaged in sharp, meaningful conversation. From candid exchanges on scaling global capability operations to spontaneous problem-solving huddles, the evening flowed with energy and intent.`,      
      description2: `The success of the mixer reinforced the purpose of the GCC Circle - India’s foremost leadership community for CXOs, Site Heads, and senior leaders shaping the future of global capability centers. Powered by Talentiser, it is becoming a trusted space for decision-makers to engage, exchange, and expand their networks.
        This is just the beginning. More circles, more cities, and more high-calibre leadership experiences are on the way.
      `,
      leaders: [
        { "name": "Ravi Wadhwa", "company": "Founder, GCC Circle powered by Talentiser" },
        { "name": "Arushi Jindal", "company": "GCC Circle" },
        { "name": "Ipsita Dey", "company": "Talentiser" },
        { "name": "Jaideep Agarwal", "company": "Warner Bros. Discovery" },
        { "name": "Sandeep Kumar Jain", "company": "CDK Global India" },
        { "name": "Atul Arora", "company": "Crete India" },
        { "name": "Arun Dutta", "company": "HighRadius" },
        { "name": "Yogesh Sharma", "company": "Quince" },
        { "name": "Sangeetha Yanamandra", "company": "OpenText" },
        { "name": "Biju Davis", "company": "Invoice Cloud Inc." },
        { "name": "Kartik Balachandran", "company": "Providence India" },
        { "name": "Yogesh M.", "company": "Cyara" },
        { "name": "Aditya Mony", "company": "Servify" },
        { "name": "Pallavi Maheshwari", "company": "Redwood" },
        { "name": "Shrinivas Bairi", "company": "Plume Design Inc." },
        { "name": "Peddareddappa G", "company": "Nasuni" },
        { "name": "Laxmikanth Katheragandla", "company": "Jaggaer" },
        { "name": "Sanjeev S.", "company": "Reply" },
        { "name": "Phani Kiran", "company": "iCIMS" },
        { "name": "Anurag Garg", "company": "Ryan" },
        { "name": "Seshu Kumar Loka", "company": "Highspot" },
        { "name": "Anumolu Kiran", "company": "Kiddie Global Solutions" },
        { "name": "Yagneshwar Sreekanth", "company": "GUS Education India" },
        { "name": "Rajesh Ramaswami", "company": "Elevance Health" }
      ],
      images: [

      ]
    },
  ];